name: Azure Function CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
        package: .
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}

    - name: Configure Azure Monitor Alert for Function Failures
      run: |
        az monitor metrics alert create \
          --name FunctionFailureAlert \
          --resource-group myResourceGroup \
          --scopes /subscriptions/AA0FE123-8B31-4704-B1EF-25D23BA273B5/resourceGroups/myResourceGroup/providers/Microsoft.Web/sites/${{ secrets.AZURE_FUNCTIONAPP_NAME }} \
          --condition "count Http5xx > 0" \
          --window-size 5m \
          --evaluation-frequency 1m \
          --description "Alert when there are any function failures (5xx errors)" \
          --action /subscriptions/AA0FE123-8B31-4704-B1EF-25D23BA273B5/resourceGroups/myResourceGroup/providers/microsoft.insights/actionGroups/FunctionAlertsGroup

